const main = document.querySelector('#main-content');
const menuToggle = document.querySelector('.menu-toggle');
const mobileNav = document.querySelector('.mobile-nav');

const regionPrimary = ['Interlagos', 'Bolsão de Interlagos', 'Marajoara', 'Socorro', 'Veleiros', 'Jardim Suzana', 'Jardim Sabará', 'Miguel Yunes', 'Santo Amaro'];
const regionSecondary = ['Campo Grande', 'Jurubatuba', 'Cidade Dutra', 'Jardim Prudência', 'Vila Andrade', 'Chácara Flora', 'Alto da Boa Vista', 'Granja Julieta', 'Chácara Santo Amaro', 'Jardim dos Lagos', 'Jardim Ipanema', 'Vila São Paulo', 'Vila Castelo', 'Jardim Umuarama', 'Jardim Taquaral'];

function propertyCard(property) {
  return `<article class="property-card"><a href="#/imovel/${property.id}"><img src="${property.image}" alt="${property.title}" loading="lazy"><div class="property-info"><div class="property-meta">${property.type} · ${property.neighborhood}</div><h3>${property.title}</h3><div class="property-meta">${property.bedrooms ? `${property.bedrooms} dormitórios · ` : ''}${property.parking ? `${property.parking} vagas · ` : ''}${property.area}</div><p class="property-price">${property.price}</p><span class="text-link">Ver imóvel</span></div></a></article>`;
}

function propertySearchPage(purpose) {
  const title = purpose === 'venda' ? 'Imóveis para comprar' : 'Imóveis para alugar';
  return `<section class="page-hero"><p class="eyebrow">${purpose === 'venda' ? 'Compra' : 'Locação'} · Zona Sul de São Paulo</p><h1>${title}</h1><p>Uma seleção de imóveis para você encontrar o próximo endereço com clareza e tranquilidade.</p></section><section class="search-results"><form class="filter-bar" data-search-form data-purpose="${purpose}"><input name="location" placeholder="Código, bairro, cidade ou condomínio" aria-label="Código, bairro, cidade ou condomínio"><select name="type" aria-label="Tipo de imóvel"><option value="">Todos os tipos</option><option>Casa</option><option>Apartamento</option><option>Terreno</option><option>Sala</option><option>Loja</option></select><button class="button button-dark" type="submit">Buscar</button></form><div class="property-grid" data-results></div><div class="search-cta"><p>${purpose === 'venda' ? 'Tem um imóvel para vender?' : 'Tem um imóvel para alugar?'}</p><a class="text-link" href="#/cadastre-seu-imovel">Anuncie seu imóvel</a></div></section>`;
}

function formPage(kind) {
  const isSell = kind === 'sell';
  const title = isSell ? 'Quer anunciar seu imóvel?' : 'Cadastre seu imóvel';
  const intro = isSell ? 'Converse com a Intersul sobre o seu imóvel. Nossa atuação na Zona Sul começa com uma escuta cuidadosa do seu objetivo.' : 'Venda, alugue ou coloque seu imóvel sob administração da Intersul.';
  return `<section class="page-hero"><p class="eyebrow">Proprietários</p><h1>${title}</h1><p>${intro}</p></section><section class="form-layout"><div><h2>${isSell ? 'Uma conversa começa aqui.' : 'Seu imóvel, o próximo capítulo.'}</h2><p>Preencha os dados iniciais para que a equipe entenda como podemos ajudar.</p></div><form class="form-panel lead-form"><div class="form-grid"><div class="field"><label for="name">Nome</label><input id="name" name="name" required></div><div class="field"><label for="phone">Telefone</label><input id="phone" name="phone" required></div><div class="field"><label for="email">E-mail</label><input id="email" name="email" type="email"></div><div class="field"><label for="purpose">Objetivo</label><select id="purpose" name="purpose"><option>Quero vender</option><option>Quero alugar</option><option>Quero administrar</option><option>Ainda não tenho certeza</option></select></div><div class="field"><label for="type">Tipo do imóvel</label><input id="type" name="type" placeholder="Casa, apartamento, terreno..."></div><div class="field"><label for="city">Cidade</label><input id="city" name="city" value="São Paulo"></div><div class="field field-full"><label for="address">Endereço</label><input id="address" name="address"></div><div class="field field-full"><label for="message">Mensagem</label><textarea id="message" name="message"></textarea></div></div><button class="button button-dark" type="submit">Enviar cadastro</button><p class="form-status" aria-live="polite"></p></form></section>`;
}

function homePage() {
  const featured = `<div class="featured-layout"><div class="featured-main">${propertyCard(demoProperties[0])}</div><div class="featured-side">${propertyCard(demoProperties[1])}${propertyCard(demoProperties[2])}</div></div><div class="featured-mini-grid">${demoProperties.slice(3, 9).map(propertyCard).join('')}</div>`;
  return `<section class="hero"><div><p class="eyebrow">Desde 2005 · Zona Sul de São Paulo</p><h1>Um mundo de imóveis<br>para você.</h1><p class="hero-copy">Vinte anos de tradição em Interlagos e na Zona Sul, com uma nova forma de encontrar o seu próximo endereço.</p></div><div class="hero-visual"><img src="https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1800&q=88" alt="Casa contemporânea com fachada iluminada"><span class="hero-caption">Arquitetura · patrimônio · proximidade</span></div></section><section class="section"><div class="section-intro"><div><p class="eyebrow">Quatro caminhos</p><h2>O próximo passo começa por uma intenção.</h2></div><p>Escolha o caminho que faz sentido para você. A experiência foi desenhada para não misturar quem procura um imóvel com quem cuida de um patrimônio.</p></div><div class="path-grid"><div class="path"><span class="path-number">01</span><h3>Comprar</h3><p>Encontre imóveis na região que você conhece ou quer descobrir.</p><a class="text-link" href="#/comprar">Explorar imóveis</a></div><div class="path"><span class="path-number">02</span><h3>Alugar</h3><p>Uma busca mais clara para encontrar seu próximo endereço.</p><a class="text-link" href="#/alugar">Ver locações</a></div><div class="path"><span class="path-number">03</span><h3>Vender</h3><p>Converse com uma equipe que conhece o território.</p><a class="text-link" href="#/vender">Quero vender</a></div><div class="path"><span class="path-number">04</span><h3>Administrar</h3><p>Seu patrimônio em boas mãos, com um atendimento próximo.</p><a class="text-link" href="#/administracao-de-imoveis">Conhecer serviço</a></div></div></section><section class="section featured-home"><div class="section-intro"><div><p class="eyebrow">Seleção Intersul</p><h2>Imóveis em destaque</h2></div><a class="text-link" href="#/comprar">Ver todos os imóveis</a></div>${featured}</section><section class="section section-dark"><div class="territory"><div><p class="eyebrow">Território de marca</p><h2>Especialistas em Interlagos e região.</h2><p>Conhecemos a Zona Sul de São Paulo e a personalidade de cada território onde atuamos.</p></div><div class="territory-list">${regionPrimary.map((region) => `<a href="#/comprar?location=${encodeURIComponent(region)}">${region}</a>`).join('')}</div></div></section><section class="section"><div class="owner-band"><div><p class="eyebrow">Para proprietários</p><h2>Seu imóvel pode estar no próximo capítulo da Intersul.</h2></div><div class="owner-aside"><p>Venda, alugue ou coloque seu imóvel sob administração da Intersul.</p><a class="button button-dark" href="#/cadastre-seu-imovel">Anuncie seu imóvel</a></div></div><div class="stats"><div class="stat"><strong>2005</strong><span>ano de fundação</span></div><div class="stat"><strong>+1.300</strong><span>imóveis no inventário institucional</span></div><div class="stat"><strong>19.777-J</strong><span>CRECI</span></div></div></section>`;
}

function aboutPage() { return `<section class="page-hero"><p class="eyebrow">A Intersul</p><h1>Experiência local para decisões importantes.</h1><p>A Intersul Imóveis atua em São Paulo desde 2005, com forte presença em Interlagos e na Zona Sul.</p></section><section class="section"><div class="territory"><div><p class="eyebrow">Conhecimento e proximidade</p><h2>Um atendimento imobiliário próximo.</h2></div><div><p>Compra, venda, locação e administração de imóveis fazem parte da atuação da Intersul.</p><p class="notice">CRECI 19.777-J · Av. Atlântica, 1893 - Interlagos, São Paulo - SP</p></div></div></section>`; }

function administrationPage() { return `<section class="page-hero"><p class="eyebrow">Administração de imóveis</p><h1>Seu patrimônio em boas mãos.</h1><p>A Intersul conversa com proprietários que desejam contar com uma imobiliária experiente para a administração de seus imóveis.</p><div class="hero-actions"><a class="button button-dark" href="#/cadastre-seu-imovel">Quero administrar meu imóvel</a><a class="button button-outline" href="#/cadastre-seu-imovel">Anuncie seu imóvel</a></div></section><section class="section"><div class="territory"><div><p class="eyebrow">Um atendimento próximo</p><h2>Mais tranquilidade para quem possui um imóvel.</h2></div><div><p>A administração começa por entender o imóvel, o momento do proprietário e o tipo de acompanhamento necessário. A equipe da Intersul orientará os próximos passos em uma conversa direta.</p><div class="notice">[DETALHAR SERVIÇOS DE ADMINISTRAÇÃO]</div></div></div></section><section class="section section-dark"><div class="owner-band"><div><p class="eyebrow">Vamos conversar</p><h2>Conte à Intersul sobre o seu patrimônio.</h2></div><div class="owner-aside"><p>O cadastro inicial foi preparado para receber o fluxo oficial de atendimento.</p><a class="button button-outline" style="border-color:white;color:white" href="#/cadastre-seu-imovel">Anuncie seu imóvel</a></div></div></section>`; }

function detailPage(id) { const property = demoProperties.find((item) => item.id === id) || demoProperties[0]; return `<section class="page-hero"><p class="eyebrow">${property.type} · ${property.neighborhood}</p><h1>${property.title}</h1><p>${property.city} · Código demonstrativo ${property.id}</p></section><section class="detail-grid"><img class="detail-image" src="${property.image}" alt="${property.title}"><div class="detail-content"><div><p class="eyebrow">${property.purpose === 'venda' ? 'À venda' : 'Para locação'}</p><h2>${property.price}</h2><div class="details-list"><span>${property.bedrooms || 'A confirmar'} dormitórios</span><span>${property.suites || 'A confirmar'} suítes</span><span>${property.parking || 'A confirmar'} vagas</span><span>${property.area}</span></div><p style="margin-top:30px">[DESCRIÇÃO COMPLETA DO IMÓVEL A CONFIRMAR]</p></div><aside class="detail-sidebar"><h3>Tenho interesse</h3><p>Fale com a equipe da Intersul sobre este imóvel.</p><a class="button button-dark" href="#/cadastre-seu-imovel">Entrar em contato</a></aside></div></section>`; }

function render() { const [path, query] = window.location.hash.replace(/^#/, '').split('?'); const params = new URLSearchParams(query); if (path === '/' || !path) { main.innerHTML = homePage(); main.querySelector('.hero').insertAdjacentHTML('afterend', `<section class="search-panel" aria-label="Busca de imóveis"><form class="search-panel-inner" data-home-search><div class="search-panel-heading"><p>Encontre seu próximo endereço</p><strong>Buscar imóveis</strong><div class="search-tabs"><button class="active" type="button" data-purpose="venda">Comprar</button><button type="button" data-purpose="aluguel">Alugar</button></div></div><div class="search-field"><label for="home-location">Localização</label><input id="home-location" name="location" placeholder="Bairro ou cidade"></div><div class="search-field"><label for="home-type">Tipo de imóvel</label><select id="home-type" name="type"><option value="">Todos os tipos</option><option>Casa</option><option>Apartamento</option><option>Terreno</option><option>Sala</option><option>Loja</option></select></div><div class="search-field"><label for="home-price">Faixa de preço</label><select id="home-price" name="price"><option value="">Qualquer valor</option><option>Até R$ 500 mil</option><option>R$ 500 mil a R$ 1 mi</option><option>Acima de R$ 1 mi</option></select></div><button class="button button-dark" type="submit">Buscar</button></form></section>`); } else if (path === '/comprar') main.innerHTML = propertySearchPage('venda'); else if (path === '/alugar') main.innerHTML = propertySearchPage('aluguel'); else if (path === '/vender') main.innerHTML = formPage('sell'); else if (path === '/cadastre-seu-imovel') main.innerHTML = formPage('register'); else if (path === '/administracao-de-imoveis') main.innerHTML = administrationPage(); else if (path === '/sobre-a-intersul') main.innerHTML = aboutPage(); else if (path.startsWith('/imovel/')) main.innerHTML = detailPage(path.split('/')[2]); else main.innerHTML = homePage(); if (path === '/comprar' || path === '/alugar') loadResults(path === '/comprar' ? 'venda' : 'aluguel', params); bindInteractions(); window.scrollTo(0, 0); }

async function loadResults(purpose, params = new URLSearchParams()) { const result = await propertyRepository.search({ purpose, location: params.get('location') || '', type: '' }); const target = document.querySelector('[data-results]'); if (target) target.innerHTML = result.items.length ? result.items.map(propertyCard).join('') : '<p class="empty">Nenhum imóvel encontrado com estes filtros.</p>'; }
function bindInteractions() { document.querySelectorAll('.lead-form').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); form.querySelector('.form-status').textContent = 'Recebemos seus dados. A equipe da Intersul entrará em contato.'; form.reset(); })); document.querySelectorAll('[data-search-form]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const params = new URLSearchParams(new FormData(form)); window.location.hash = `${window.location.hash.split('?')[0]}?${params.toString()}`; })); const homeSearch = document.querySelector('[data-home-search]'); if (homeSearch) { homeSearch.querySelectorAll('[data-purpose]').forEach((tab) => tab.addEventListener('click', () => { homeSearch.dataset.purpose = tab.dataset.purpose; homeSearch.querySelectorAll('[data-purpose]').forEach((item) => item.classList.toggle('active', item === tab)); })); homeSearch.addEventListener('submit', (event) => { event.preventDefault(); const params = new URLSearchParams(new FormData(homeSearch)); window.location.hash = `/${homeSearch.dataset.purpose === 'aluguel' ? 'alugar' : 'comprar'}?${params.toString()}`; }); } }
function formatPhone(value) { const digits = value.replace(/\D/g, '').slice(0, 11); if (digits.length <= 2) return digits.length ? `(${digits}` : ''; if (digits.length <= 6) return `(${digits.slice(0, 2)}) ${digits.slice(2)}`; if (digits.length <= 10) return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`; return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`; }
function initializeGoogleAddressAutocomplete(address) { if (!address || address.dataset.googleAutocomplete || !window.google?.maps?.places?.Autocomplete) return; new window.google.maps.places.Autocomplete(address, { types: ['address'], componentRestrictions: { country: 'br' } }); address.dataset.googleAutocomplete = 'true'; }
function initializeAddressSuggestions(address) { if (!address || address.dataset.suggestionsReady || window.google?.maps?.places?.Autocomplete) return; const listId = 'address-suggestions'; let datalist = document.getElementById(listId); if (!datalist) { datalist = document.createElement('datalist'); datalist.id = listId; document.body.appendChild(datalist); } address.setAttribute('list', listId); address.dataset.suggestionsReady = 'true'; let timer; address.addEventListener('input', () => { clearTimeout(timer); const query = address.value.trim(); if (query.length < 3) { datalist.replaceChildren(); return; } timer = setTimeout(async () => { try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=br&limit=6&addressdetails=1&q=${encodeURIComponent(query)}`); if (!response.ok) return; const results = await response.json(); datalist.replaceChildren(...results.map((result) => { const option = document.createElement('option'); option.value = result.display_name; return option; })); } catch (error) { datalist.replaceChildren(); } }, 300); }); }
function initializeCepLookup(address, city) { if (!address || !city || address.dataset.cepLookup) return; city.value = ''; city.placeholder = 'Cidade'; address.dataset.cepLookup = 'true'; address.addEventListener('input', async () => { const cep = address.value.replace(/\D/g, ''); if (cep.length !== 8) return; try { const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`); if (!response.ok) return; const result = await response.json(); if (result.erro) return; address.value = result.logradouro || ''; city.value = result.localidade || ''; address.dispatchEvent(new Event('change', { bubbles: true })); city.dispatchEvent(new Event('change', { bubbles: true })); } catch (error) { /* Keeps manual address entry available when the lookup is unavailable. */ } }); }
function enhanceOwnerForm() { const phone = document.querySelector('#phone'); if (phone && !phone.dataset.masked) { phone.type = 'tel'; phone.inputMode = 'tel'; phone.autocomplete = 'tel'; phone.placeholder = '(11) 99999-9999'; phone.dataset.masked = 'true'; phone.addEventListener('input', () => { phone.value = formatPhone(phone.value); }); } const address = document.querySelector('#address'); const city = document.querySelector('#city'); const message = document.querySelector('#message'); if (!address || !city || !message || document.querySelector('#number')) return; address.placeholder = 'Nome da rua ou CEP'; address.setAttribute('autocomplete', 'street-address'); address.setAttribute('data-address-autocomplete', ''); initializeGoogleAddressAutocomplete(address); initializeAddressSuggestions(address); initializeCepLookup(address, city); const addressField = address.closest('.field'); addressField.classList.remove('field-full'); const messageField = message.closest('.field'); const numberField = document.createElement('div'); numberField.className = 'field'; numberField.innerHTML = '<label for="number">Número</label><input id="number" name="number" placeholder="Número do imóvel" inputmode="numeric" autocomplete="address-line2">'; const complementField = document.createElement('div'); complementField.className = 'field field-full'; complementField.innerHTML = '<label for="complement">Complemento</label><input id="complement" name="complement" placeholder="Nº Apto - Bloco - Condomínio">'; messageField.before(numberField, complementField); }
function normalizeHomeSearchPlaceholder() { const input = document.querySelector('#home-location'); if (input) { input.placeholder = 'Código, bairro, cidade ou condomínio'; input.setAttribute('aria-label', 'Código, bairro, cidade ou condomínio'); } enhanceOwnerForm(); }
const searchPlaceholderObserver = new MutationObserver(normalizeHomeSearchPlaceholder);
searchPlaceholderObserver.observe(main, { childList: true, subtree: true });
menuToggle.addEventListener('click', () => { const open = mobileNav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(open)); });
window.addEventListener('hashchange', render); render();
